version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: bike_exchange_db
    environment:
      MYSQL_DATABASE: bike_exchange_prod
      MYSQL_ROOT_PASSWORD: secretpassword
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: bike_exchange_redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: bike_exchange_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/bike_exchange_prod?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secretpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - JWT_SECRET=BE713365926D96C90030DD58429D2751AC1BDBBC926D96C90030DD58429D2751AC1BDBBC
      - JWT_EXPIRATION_MS=86400000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  mysqldata:
