spring:
  application:
    name: BikeExchange-Backend

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:bike_exchange}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:12345678}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  mvc:
    throw-exception-if-no-handler-found: true

server:
  servlet:
    context-path: /api
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: INFO
    com.bikeexchange: DEBUG
    org.hibernate.tool.schema: WARN
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO

app:
  jwtSecret: ${JWT_SECRET:926D96C90030DD58429D2751AC1BDBBC926D96C90030DD58429D2751AC1BDBBC}
  jwtExpirationMs: ${JWT_EXPIRATION_MS:86400000}
